# Generated by Django 5.1.2 on 2024-10-09 17:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("department", models.CharField(max_length=40)),
                ("mobile", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=12)),
                ("age", models.IntegerField()),
                ("reason", models.CharField(default="Unknown", max_length=700)),
                ("mobile", models.IntegerField(null=True)),
                ("admission", models.DateField(default=django.utils.timezone.now)),
                ("discharge", models.DateField(default=django.utils.timezone.now)),
                ("docname", models.CharField(default="Unknown Doctor", max_length=100)),
                (
                    "prescription",
                    models.CharField(default="No prescription", max_length=700),
                ),
                ("bill", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date1", models.DateField()),
                ("time1", models.TimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Hospital.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Hospital.patient",
                    ),
                ),
            ],
        ),
    ]
