# Generated by Django 5.1.2 on 2024-10-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="patient",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="prescription",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="mobile",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="admission",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="discharge",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="docname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Hospital.doctor"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="mobile",
            field=models.CharField(default="0000000000", max_length=15),
        ),
        migrations.AlterField(
            model_name="patient",
            name="reason",
            field=models.CharField(max_length=255),
        ),
    ]
